// <auto-generated />
namespace tranminhtrung_2011061212.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class khoitaocacbangchucnangchungthucnguoidung : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(khoitaocacbangchucnangchungthucnguoidung));
        
        string IMigrationMetadata.Id
        {
            get { return "202303100128023_khoi tao cac bang chuc nang chung thuc nguoi dung"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
